credentials = "common-service-account.json"
google_bucket_name = "safag-05-bucket"
deployment_name = "hello-world"
google_project_id = "my-fuchi-pro"
google_domain_name = "g-safa.com"
deployment_environment = "dev"